### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by zhangyunming** [senguptaumd/Background-Matting#1]
hi, 
    if i have a picture with one persion(_img.png), but i have no the corresponding pic of background(_back.png),  can i do the background-matting? because in real life , we just take the picture(_img.png) without background（_back.png）,thanks.

**Comment by senguptaumd** [comment]
Hi,
This method can not be applied to existing photos or videos. The idea is: if your goal is to use green-screen technology, aka replace the background, you will capture photos/videos with that in mind. While capturing you will take an additional photo of the background. 

Traditional image matting methods do not need an extra background. But they need the user to annotate the detailed trimap (which is used in Photoshop). But this is very hard to do, especially for videos. Thus for videos green screen is the most commonly used technique. But green screen requires a studio setup, and quality can vary depending on the setup. In contrast, we propose a technique that lets you perform a 'high' quality green screen, without the need for any green screen studio.

However, if you have an existing video where the foreground subject undergoes significant motion, s.t. either the background is completely revealed or the background can be inpainted using existing Video Inpainting techniques, you can apply our algorithm using that estimated background. Depending on a particular video and quality of inpainting, the results can be good or bad.
