### ISSUE TITLE
What does rcnn=np.delete(rcnn, range(reso[0],reso[0]+K), 0) do?

### ISSUE THREAD

**Issue by bongbonglemon** [senguptaumd/Background-Matting#10]
`rcnn=np.delete(rcnn, range(reso[0],reso[0]+K), 0)`
Why do you have this line of code for the segmentation mask?

**Comment by senguptaumd** [comment]
Segmentation mask, obtained by Deeplab, often misses the last few (say 25) rows of the image, even if there is a foreground. Then the matting result also seems to miss those last few rows and the foreground appears to be floating. This is a small hack to fix the segmentation. We delete the last 25 rows of the segmentation, then do copyBorder() to make sure the segmentation mask extends till the last row of the image. Then we erode-dilate the segmentation, pass it through Gaussian filtering to obtain a soft segmentation, aka probability of foreground. All we need is to make sure that the soft-segmentation input to the network is 1 when the foreground is present in the last few rows.

**Comment by bongbonglemon** [comment]
Does this happen with DeepLab for only certain images? It seems to work with the images in your sample_data. Or am I misunderstanding what you mean by "misses the last few".

**Comment by senguptaumd** [comment]
Yes, it happens for certain cases only, e.g. when a person is standing and the legs are in the last rows of the image. I noticed that in those cases the segmentation does not extend all the way to the last row of the image.
