### ISSUE TITLE
Question about video result

### ISSUE THREAD

**Issue by zdaiot** [senguptaumd/Background-Matting#12]
Hello, according to your latest code and video examples, I ran the results. But the result doesn't seem to be very good. 

As shown in the following picture, there will be some blanks next to the character's hair. 

![1427_img](https://user-images.githubusercontent.com/40540467/78980891-6547e780-7b51-11ea-9708-8166d124e305.png)

This is even more obvious when using my own dataset.

Do you have any suggestions?

**Comment by senguptaumd** [comment]
Hi, there certain frames where matting around the hair is not going to be perfect. This scene was quite challenging, considering the hair was moving a lot and the background was an unconstrained outdoor scene captured with a hand-held camera.

You will get better results with indoor backgrounds captured with a fixed camera on a tripod. If you have no restrictions in capturing your data and your only concern is getting a great result, here are my suggestion:
Capture with a fixed camera on a tripod, choose the background to be walls. Make sure the background and foreground are of complementary colors (white wall for black hair, dark walls for blond hair). Stand at least 5ft away from the walls, make sure the subject is not casting shadows or reflection on the background. In summary, you have to follow the basic guidelines of a green screen studio, except you do not need the green screen for the best results.

**Comment by zdaiot** [comment]
Thanks a lot
