### ISSUE TITLE
What's the point of M = {I,I,I,I}?

### ISSUE THREAD

**Issue by bongbonglemon** [senguptaumd/Background-Matting#13]
Was the effects of leaving M behind studied for single-images? From what I see, it looks like it was left behind for the sake of being able to use the model for both photo and video. Yet it seems that this would cause some bias seens the model would have seen 4 duplicate channels of the same image on top of the 3 colored channels of the original image.

**Comment by senguptaumd** [comment]
It is was trained on videos where M were 4 adjoining frames. For images we simply replaced it with M={I,I,I,I}. The network was trained to focus on the difference between I and M, and ignore the rest.

Removing M for image only model may produce slightly better results, but for our paper, we choose to keep 1 model that works for images and videos.
