### ISSUE TITLE
What does it mean to set α = 1 everywhere for GReal?

### ISSUE THREAD

**Issue by bongbonglemon** [senguptaumd/Background-Matting#18]
So GReal also ouputs F, α but we set α to 1's...wouldn't that mean our composite will just be the foreground (with a black background)? Is that you mean by "would result in simply
copying the entire input image into the composite passed
to D" because I don't see why it is "indeed real". 

Thank you once again! Really appreciate your replies :)

**Comment by senguptaumd** [comment]
It means that, while training on real data with only adversarial loss, the network could produce alpha=1, along with F=I everywhere on the image. It means during composition you basically copy the original image and ignore the new background. This image is still real to the discriminator.
