### ISSUE TITLE
windows env conda support?

### ISSUE THREAD

**Issue by bitcoin5000** [senguptaumd/Background-Matting#19]
How to run on windows? seems path problem 

Background-Matting-master\Models\real-fixed-cam>export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim
'export' is not recognized as an internal or external command,
operable program or batch file.

Can it be work in google colab?

**Comment by senguptaumd** [comment]
May be this helps:
https://github.com/senguptaumd/Background-Matting/issues/3#issuecomment-609993273

**Comment by bitcoin5000** [comment]
> May be this helps:
> [#3 (comment)](https://github.com/senguptaumd/Background-Matting/issues/3#issuecomment-609993273)
thanks, 
'set Var=C:\DeepBaackground\Background-Matting-master\models\research:C:\DeepBaackground\Background-Matting-master\models\research\slim'
right?
How to install cudnn and cuda corectly in windows cuda env? im geting error


KeyError: 'CUDA_VISIBLE_DEVICES'

>   File "test_background-matting_image.py", line 20, in <module>
    print('CUDA Device: ' + os.environ["CUDA_VISIBLE_DEVICES"])
  File "C:\ProgramData\Anaconda3\envs\tensorflow_gpuenv\lib\os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'CUDA_VISIBLE_DEVICES'

**Comment by Teravus** [comment]
If your cuda processing video card is the only one in the machine, likely, you will need to do
'set CUDA_VISIBLE_DEVICES=0'

the '0' in the last command is the CUDA device id.   Most commonly 0 on computers with only one cuda capable video card.  It can be 1 or 2 or 3 or 4...  depending on how many video cards your system has.

**Comment by Teravus** [comment]
Also, for windows, there is no 'export' command.    The closest thing to what export does is 'set' 

So..   'export PYTHONPATH=thing' becomes 'set PYTHONPATH=thing'
Hopefully this is helpful.

Both set and export create environment variables.   These are then used by the code to take actions.

**Comment by senguptaumd** [comment]
We have a colab demo that you can easily run, instead of trying to install in on windows. Colab demo is decently fast for images, slow for 60fps video. Closing the issue.
