### ISSUE TITLE
TensorFlow version

### ISSUE THREAD

**Issue by gruossomonica** [senguptaumd/Background-Matting#2]
Hi, 
are you sure about the version of TensorFlow using CUDA 10.0? Tensorflow 1.4 requires CUDA 8.
I think you meant version 1.14. 
I'm trying with 1.15 and now it works well.

**Comment by senguptaumd** [comment]
Hi,
You are right. That was a typo. It will be tensorflow=1.14 with CUDA10.0. Thanks for pointing that out. Corrected it in the README.

**Comment by Teravus** [comment]
I could be wrong, but the readme may require *two* equal signs for the version.   tensorflow==1.14
