### ISSUE TITLE
Higher Crop Resolution + Congrats!

### ISSUE THREAD

**Issue by policarpobaquera** [senguptaumd/Background-Matting#21]
Hello guys,
I am a student at Carnegie Mellon University working right now on a video performance piece for one of my classes and I am completely blown away by this algorithm.  It took me some time to make CUDA work on my PC, but after that, it worked perfectly using the image mode. Here, a short clip with the results (edited in Premiere): 

https://vimeo.com/407383245

[![gif](https://user-images.githubusercontent.com/59744033/79173116-a3007680-7dc4-11ea-8cb7-82428d949d54.gif)](https://vimeo.com/407383245)

I only would like to know if it is possible to change the 512x512 crop resolution to a higher value, so it can track a bigger motion area in the original image/video.

Thanks!

**Comment by senguptaumd** [comment]
I am really happy that you could try it on your own images.  The network is trained with 512x512 resolution, so using higher input resolution may reduce the quality of the matting (I tried it before and saw that 1024x1024 produces worse results). However, the way it works is: given an image of any resolution, it crops out a 512x512 region that contains all the humans. Then it passes this image through the network and finally uncrop the output and put it back to original resolution. While cropping a 512x512 region in test_pre_process_video.py, it uses create_bbox() in L36 functions.py to create a bounding box around the human mask. You can change the crop width 'x1=bbox_init[0]-0.1*w' to 'x1=bbox_init[0]-0.3*w' in  L40 and similarly in L41,43,44 to obtain a less tighter crop. In that way you can obtain a bigger motion area.

About the quality of the results:
- There are strong reflections of the foot on the wooden floor. Usually, any feet has shadows on the floor and thus we did not include it in our training data. Surprised that it still works for those cases.
- The sofa probably shifted as the person get up, it is quite challenging
- Not that great with 'wearing helmet' and 'wearing shoes' motion. Wondering if a bigger crop area can help, especially 'wearing helmet'.

**Comment by policarpobaquera** [comment]
Noted. Thanks for the answer!
