### ISSUE TITLE
Background-Matting without CUDA?

### ISSUE THREAD

**Issue by vedmin** [senguptaumd/Background-Matting#24]
Is it possible to run Background-Matting without CUDA-enabled GPU?

**Comment by senguptaumd** [comment]
I have not tested that. But the code has multiple cuda calls and it might need correction to make it work without cuda.

**Comment by vedmin** [comment]
Thank you for the answer. 
So it seems that I can not run it on a laptop with integrated Intel GPU, as it is not CUDA-enabled.

**Comment by coding-ai** [comment]
Hey @vedmin! I have managed to run the code CPU-based. Just make sure you specify `map_location=torch.device('cpu')` the `netM.load_state_dict(torch.load(model_name1,map_location=torch.device('cpu')))` function and remove all instances that send processes directly to the GPU via `.cuda()`. Hope that helps you!
