### ISSUE TITLE
There are two person in front of camer, always missing one.

### ISSUE THREAD

**Issue by uniyushu** [senguptaumd/Background-Matting#25]
I capture the videos to use my iPhone XR fixed and follow the rules. but when I run test_background-matting_image.py, the output file always missing one person no matter how close they are. 
![0021_out](https://user-images.githubusercontent.com/20262193/79523135-0d990700-8090-11ea-8fe9-0422d52444ea.png)
![0023_out](https://user-images.githubusercontent.com/20262193/79523146-125dbb00-8090-11ea-8f18-71771107bda3.png)

**Comment by senguptaumd** [comment]
Comment L175 in test_background-matting_image.py and re-run. This keeps the largest connected component, which is not ideal when you have more than 1 person. Let me know if this works.

**Comment by uniyushu** [comment]
> Comment L175 in test_background-matting_image.py and re-run. This keeps the largest connected component, which is not ideal when you have more than 1 person. Let me know if this works.

It works, thanks.
