### ISSUE TITLE
Colab notebook

### ISSUE THREAD

**Issue by loretoparisi** [senguptaumd/Background-Matting#26]
Thank you for this amazing project!
Due to the complexity to run the inference, it would be worth to have a Colab notebook like the recent [[CVPR 2020] 3D Photography using Context-aware Layered Depth Inpainting](https://colab.research.google.com/drive/1706ToQrkIZshRSJSHvZ1RuCiM__YX3Bz)

**Comment by senguptaumd** [comment]
Thank you for your suggestion. That is definitely on my TODO list.

**Comment by petrusinov** [comment]
I can’t download this repository in google colab. I would be very grateful if someone uploads this project to the laptop colab

**Comment by senguptaumd** [comment]
Andrey Ryabtsev, University of Washington, created a google colab for this project, where you can upload images and videos both. I did not get time to test it yet. Feel free to try it out and report any issue if they arise.

**Comment by loretoparisi** [comment]
@senguptaumd do you have the link? Thanks.

**Comment by senguptaumd** [comment]
https://gist.github.com/andreyryabtsev/243aa3eefa6e06891dda7b1583d1d08f

**Comment by loretoparisi** [comment]
@senguptaumd so it seems I'm almost here. It seems it cannot find

```
python3: can't open file 'test_segmentation_deeplab.py': [Errno 2] No such file or directory
```

Current dir is `/content`.

<img width="1130" alt="Schermata 2020-04-21 alle 15 06 43" src="https://user-images.githubusercontent.com/163333/79869553-d2753b80-83e1-11ea-9365-48b15cf463b2.png">

**Comment by loretoparisi** [comment]
@senguptaumd solved that the repo clone failed. Now it's ok...

At this point I get an error
```
!CUDA_VISIBLE_DEVICES=0 python test_background-matting_image.py -m real-hand-held -i colab_inputs/input/ -o colab_inputs/output/ -tb colab_inputs/background/0001.png
```

with error:

```
CUDA Device: 0
Using image mode
Traceback (most recent call last):
  File "test_background-matting_image.py", line 46, in <module>
    back_img10=cv2.imread(args.target_back); back_img10=cv2.cvtColor(back_img10,cv2.COLOR_BGR2RGB);
cv2.error: OpenCV(4.1.2) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
```

**Comment by andreyryabtsev** [comment]
Hi @loretoparisi ! The error most likely has to do with a missing file at `colab_inputs/background/0001.png`,  -- were you able to upload this file? This would be the target background onto which to paste the resulting matte. You can also change that path in the cell if you named it something else.

**Comment by loretoparisi** [comment]
@andreyryabtsev yes it works thank you! It was due the a disconnected colab that deleted all upload contents!
