### ISSUE TITLE
Why implemented results are so terrible?

### ISSUE THREAD

**Issue by tczuo** [senguptaumd/Background-Matting#3]
Following README.md, I re-implement test phase using sampled data（author offered）and real-fixed-cam model file. The results from deeplabV3 is good , but the matting results are pretty bad, is author upload a wrong model file?
 
![img_seg](https://user-images.githubusercontent.com/9945763/78554942-a6cd4f80-783e-11ea-8256-9d37542ca061.png)
![fg](https://user-images.githubusercontent.com/9945763/78555183-0fb4c780-783f-11ea-98d1-a42c069f5535.png)

**Comment by senguptaumd** [comment]
These images are collected with hand-held camera, so you need to use 'real-hand-held' model file. Also, the image and the background are unaligned. Did you also align them based on 'python test_pre_process.py -i sample_data/input'?

**Comment by cyberpsyche** [comment]
Me two.  The results are unacceptable compare to the sampled data demos shiped with the source code. I tried several type of foreground and background images inside and oudside of doo r with virious illumations, but the results are totally cannot compete with the demos. What's the matter with the model?

**Comment by senguptaumd** [comment]
Hi,

First of all, can you clarify if the results are also bad on the provided 'sampled_data'. If yes that will indicate that either you did not go through the alignment process or you choose a wrong model. I tested on these images so it should be fine. Please let me know if the provided code works on the provided images.

Next, for new images, for best results, the data collection step needs to follow the guidelines. Would you mind sharing some images and results with me at soumya91@cs.washington.edu? I would like to take a look at it.

**Comment by senguptaumd** [comment]
@tczuo I verified the model and the code. You got this result because: (i) You did not align the background with the image as suggested in pre-processing (see README) (ii) You used the fixed-camera model and not hand-held. Let me know if it works for you.

@cyberpsyche I am guessing you were successful in getting good results on the sampled_data. As for new images, make sure you followed the guidelines in README. Few issues: (a) not locking AE/AF of the camera. (b) Strong shadows on the backdrop (c) Non-static background, can cause the results to be worse. 
Would you mind sharing some images and results with me at soumya91@cs.washington.edu? I would like to take a look at it to understand why it produces bad results. I tested on 50 captured videos, which I will also release soon.

**Comment by Teravus** [comment]
I tested the sample on Windows 10 on a Geforce GTX 2080 ti and it produced the 'good' result that I saw on the project page.  

There were a few minor additional things that I had to do.
I had to install opencv-python and CUDA version 7 for deeplab to work.
I had to update my version of CuDNN to 7.4.1

I had to export the Environment variables using 'set Var=value' because Windows.
I had to follow the directions on the Readme in github.

**Comment by senguptaumd** [comment]
@Teravus Thanks for letting me know.

opencv-python should have been installed via 'pip install -r requirements.txt'.
Deeplab works for me with CUDA10. Not sure if you specifically need CUDA7.

I will include the CuDNN version and windows environment variable set in the README.

**Comment by tczuo** [comment]
Thank you very much. According to your two helpful suggestions, I get good results as same as yours.  But I found that if using  fixed-camera model (You said it it the best model), the result is not good (please see following image). I will  try to test fixed-camera model using my images (photoed by  fixed-camera).

![image](https://user-images.githubusercontent.com/9945763/78619951-4aefde80-78b1-11ea-9ea0-e7c4292aeed6.png)

> @tczuo I verified the model and the code. You got this result because: (i) You did not align the background with the image as suggested in pre-processing (see README) (ii) You used the fixed-camera model and not hand-held. Let me know if it works for you.
> 
> @cyberpsyche I am guessing you were successful in getting good results on the sampled_data. As for new images, make sure you followed the guidelines in README. Few issues: (a) not locking AE/AF of the camera. (b) Strong shadows on the backdrop (c) Non-static background, can cause the results to be worse.
> Would you mind sharing some images and results with me at [soumya91@cs.washington.edu](mailto:soumya91@cs.washington.edu)? I would like to take a look at it to understand why it produces bad results. I tested on 50 captured videos, which I will also release soon.

**Comment by senguptaumd** [comment]
Hi @tczuo 'fixed-camera-model' was trained without any hand-held data, so it is not robust to small misalignment. The sampled_data images are all hand-held captured, so it will perform best with hand-held model and not fixed-camera model. If you want to try this on your own data, choose the model based on whether the data is hand-held or fixed-camera. In general, the method performs better when images are captured with fixed camera.

**Comment by senguptaumd** [comment]
@tczuo why do you have a black background? '_fg' is not the final matte, it is the predicted foreground. '_out' is the predicted alpha channel. '_matte' is the result of compositing the foreground '_fg' on a green screen with alpha channel '_alpha'.

This is the final matting result you should get.
![0_matte](https://user-images.githubusercontent.com/34743495/78620688-b0f74a00-784e-11ea-9583-5719c22fed3d.png)

**Comment by senguptaumd** [comment]
This is foreground
![0_fg](https://user-images.githubusercontent.com/34743495/78620727-c9676480-784e-11ea-9fe5-f332a1980b4f.png)
 This is the alpha matte
![0_out](https://user-images.githubusercontent.com/34743495/78620739-d1270900-784e-11ea-96e0-fa05f30418f3.png)

**Comment by tczuo** [comment]
Hi  @cyberpsyche. Thanks for your patient and effective reply. I have got wonderful  matting result as yours using hand-hold model. Because 'fixed-camera-model' was trained without any hand-held data, it is normal that the result have a little problem. So, I close this issue.

> This is foreground
> ![0_fg](https://user-images.githubusercontent.com/34743495/78620727-c9676480-784e-11ea-9fe5-f332a1980b4f.png)
> This is the alpha matte
> ![0_out](https://user-images.githubusercontent.com/34743495/78620739-d1270900-784e-11ea-96e0-fa05f30418f3.png)
