### ISSUE TITLE
Output foreground vs original foreground

### ISSUE THREAD

**Issue by emepetres** [senguptaumd/Background-Matting#32]
Hi, question:

What's the difference between the output foreground, and let's say getting original pixels * (alpha > 0.95)? Is the network changing somehow the color information in the output?

Thanks!

**Comment by senguptaumd** [comment]
This is just to make sure if for some reason the foreground prediction is terrible on pixels that are definitely foreground, e.g. alpha>0.95, we can copy it directly from the image. Ideally, the network will learn it. You can remove it and it will work for most of the cases.

**Comment by emepetres** [comment]
I see @senguptaumd, but I still don't understand why I should use the preditected foreground output, instead of doing `original image * alpha`. I mean, what's the difference between the two, qualitative speaking?

Thanks!

**Comment by senguptaumd** [comment]
Around the edges where alpha is not 1, if you use original_image*alpha, you are not actually separating the color. For example, if you capture a person with black hair in front of a bright window, the hair edges will contain traces of white lighting, if you compose it now on a dark background without separating the color, you will notice a white halo. Check our paper's supplementary material where we clarified why predicting F is important with an example.

**Comment by emepetres** [comment]
great, thnks!
