### ISSUE TITLE
Is the matting real-time?

### ISSUE THREAD

**Issue by jayavanth** [senguptaumd/Background-Matting#35]
I was wondering if I can use it for video streaming

**Comment by senguptaumd** [comment]
Not really, work needs to be done to make it realtime (>30fps or >60fps)

**Comment by viral98** [comment]
Could you specify what sort of work needs to be done to make it realtime? I was wondering if this could be integrated with webcamoid to solve this [issue](https://github.com/webcamoid/webcamoid/issues/250)

**Comment by kwea123** [comment]
So what is the speed on your GPU currently? Having a number can help to estimate what should be improved.

**Comment by senguptaumd** [comment]
Please see this discussion about current runtime statistics  #41 . We are working to improve the system and make it real-time in the near future.
