### ISSUE TITLE
Question: why should we predict foreground color?

### ISSUE THREAD

**Issue by mozpp** [senguptaumd/Background-Matting#39]
why should we predict foreground color? I think we can compute it by alpha and input image.

**Comment by senguptaumd** [comment]
Please check the supplementary of the paper where we discuss why it is important to also predict the foreground.
[choice_of_F.pdf](https://github.com/senguptaumd/Background-Matting/files/4641182/choice_of_F.pdf)

**Comment by senguptaumd** [comment]
Also check #32
