### ISSUE TITLE
Very cool technology, is there hope to be implemented on the mobile terminal (iOS / Android)?

### ISSUE THREAD

**Issue by Jinxiansen** [senguptaumd/Background-Matting#44]
Very cool technology, is there hope to be implemented on the mobile terminal (iOS / Android)? 
Or are there any ideas or reference programs that can be used for reference.

Thank you very much!

> English is not my native language; please excuse typing errors.

**Comment by senguptaumd** [comment]
we are working on a network that can run on mobile devices in real-time. We do not have any iOS/Android implementation now.

**Comment by Jinxiansen** [comment]
Oh, looking forward to your work!

**Comment by Shanky1922** [comment]
Just checking to see if there's any update on using it on Mobile Application yet?

Or I just have to convert it in tflite and use it to see how it's working and all?
