### ISSUE TITLE
demo image is perfect but for my image it has some problem.

### ISSUE THREAD

**Issue by wuboris** [senguptaumd/Background-Matting#5]
![0001_masksDL](https://user-images.githubusercontent.com/13932472/78633523-6fa97d80-78d4-11ea-9967-c9858a01caae.png)
![0_out](https://user-images.githubusercontent.com/13932472/78633535-7637f500-78d4-11ea-9282-d82a9fb7bb11.png)
the first mask is generate by my FCN, the second mask is generate by Background-Matting.  Moreover, the size of image is change.

**Comment by senguptaumd** [comment]
@wuboris Is the Background-MAtting mask 512x512? Then it seems like you have disabled the resizing. It usually takes the segmentation, crops a 512x512 region around it, pass it through the network and then uncrop the output back to the original resolution.

Please follow https://github.com/senguptaumd/Background-Matting#notes-on-capturing-images  for capturing images. It seems like you either have a very strong reflection or shadows on the backdrop. You need to avoid that. Traditional green-screen also avoid shadows or reflection on the backdrop.

**Comment by senguptaumd** [comment]
Fixed the cropping/aspect ratio issue. Hopefully, now it works better.

**Comment by senguptaumd** [comment]
Check the latest update and see if it helps.

**Comment by wuboris** [comment]
great，thankyou for your help
