### ISSUE TITLE
can it run from video to video?

### ISSUE THREAD

**Issue by PeopleComeAndGo** [senguptaumd/Background-Matting#6]
hi, saw this interesting work in git trending. wonderful work.
from the sampledata, it seems the bachground matting is pic to pic.
can it run from video to video? (input the video and output the target video)?

**Comment by senguptaumd** [comment]
Yes. By the end of the week, I plan to release a demo wrapper code on how to run it directly on videos. We will also release more captured videos under different settings to help users understand what is the best capture setup. I will let you know here.

**Comment by senguptaumd** [comment]
Video to Video code is online now :) Hope it helps
