### ISSUE TITLE
MSCOCO

### ISSUE THREAD

**Issue by leemengxing** [senguptaumd/Background-Matting#67]
hi：
      MSCOCO as a background image，Wouldn't it be a problem if one person in MSCOCO background？Thanks for the answer.

**Comment by senguptaumd** [comment]
Not really as we also take a segmentation and background as input. You can also try Places2 dataset which can potentially produce a slightly better result (we observed that after this code was published)

**Comment by leemengxing** [comment]
thks，Indeed. I will try the Places2 dataset.
