### ISSUE TITLE
shape miss，After Update（4.8）

### ISSUE THREAD

**Issue by jjandnn** [senguptaumd/Background-Matting#9]
CUDA Device: 0
Using image mode
Traceback (most recent call last):
  File "test_background-matting_image.py", line 179, in <module>
    comp_im_tr1=composite4(fg_out0,back_img10,alpha_out0)
  File "/content/drive/My Drive/Background-Matting/functions.py", line 8, in composite4
    im = alpha * fg + (1 - alpha) * bg
ValueError: operands could not be broadcast together with shapes (1080,1920,1) (1080,1980,3) 

background/0002.png miss.
0001.png is ok.

**Comment by senguptaumd** [comment]
Error with only 0002.png, you mean? It works with 0001.png, right?

I will fix it soon. Thanks for bringing it to notice.

**Comment by jjandnn** [comment]
Error with only 0002.png。
thanks。
Your project is really great. Good luck。

**Comment by senguptaumd** [comment]
Thanks for the detailed bug report. Fixed it :)

**Comment by jjandnn** [comment]
The boss hard！
